DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers (
	id INT NOT NULL
	AUTO_INCREMENT,
  	burger_name VARCHAR
	(50) NOT NULL,
  	devoured BOOLEAN NOT NULL DEFAULT false,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	PRIMARY KEY(id)
);


SELECT * FROM burgers;